<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 7.2.2 (Python 3.13.2 on darwin)" generated="2025-04-01T17:43:27.127029" rpa="false" schemaversion="5">
<suite id="s1" name="Test Json" source="/Users/magnet/IdeaProjects/test/4_test_cases/test_json.robot">
<test id="s1-t1" name="Validate JSON Parameters" line="14">
<kw name="Validate Json" owner="json_utils">
<msg time="2025-04-01T17:43:27.428293" level="FAIL">Unexpected error: Error: `respDesc` has value `Invalid User ID`, expected `""`.</msg>
<arg>${JSON_DATA}</arg>
<arg>${BASE_PARAM}</arg>
<arg>${SUB_PARAMS}</arg>
<arg>${SUB_PARAMS_VALUE}</arg>
<status status="FAIL" start="2025-04-01T17:43:27.428100" elapsed="0.001131">Unexpected error: Error: `respDesc` has value `Invalid User ID`, expected `""`.</status>
</kw>
<status status="FAIL" start="2025-04-01T17:43:27.427395" elapsed="0.001952">Unexpected error: Error: `respDesc` has value `Invalid User ID`, expected `""`.</status>
</test>
<status status="FAIL" start="2025-04-01T17:43:27.134031" elapsed="0.295532"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat name="Test Json" id="s1" pass="0" fail="1" skip="0">Test Json</stat>
</suite>
</statistics>
<errors>
</errors>
</robot>
